In [1]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import f1_score
from sklearn import preprocessing
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import math

In [2]:
# recall = poder do classificador de encontrar todos os positivos

# SA Heart

In [3]:
df1 = pd.read_csv("./../SAheart.data", sep=',') 

In [4]:
df1.columns

Index(['sbp', 'tobacco', 'ldl', 'adiposity', 'famhist', 'typea', 'obesity',
       'alcohol', 'age', 'chd'],
      dtype='object')

In [5]:
le = preprocessing.LabelEncoder()
df1.famhist = le.fit_transform(df1.famhist)

In [6]:
df1.head(5)

sbp  tobacco   ldl  adiposity  famhist  typea  obesity  alcohol  age  chd
1  160    12.00  5.73      23.11        1     49    25.30    97.20   52    1
2  144     0.01  4.41      28.61        0     55    28.87     2.06   63    1
3  118     0.08  3.48      32.28        1     52    29.14     3.81   46    0
4  170     7.50  6.41      38.03        1     51    31.99    24.26   58    1
5  134    13.60  3.50      27.78        1     60    25.99    57.34   49    1

In [7]:
X = df1.drop(["chd"],axis=1)
#X = df1[['age','obesity']]
y = df1["chd"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, shuffle=True)

### Logistic Regression

In [8]:
lr_clf = LogisticRegression(max_iter=2000)
lr_clf.fit(X_train,y_train)

/home/gykimura/miniconda3/envs/boticario/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=2000,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [9]:
pred_train = lr_clf.predict(X_train)
pred_test = lr_clf.predict(X_test)

In [10]:
cm = confusion_matrix(y_train, pred_train)
cm

array([[227,  36],
       [ 73,  56]])

In [11]:
print(classification_report(y_train, pred_train))

              precision    recall  f1-score   support

           0       0.76      0.86      0.81       263
           1       0.61      0.43      0.51       129

    accuracy                           0.72       392
   macro avg       0.68      0.65      0.66       392
weighted avg       0.71      0.72      0.71       392



In [12]:
cm = confusion_matrix(y_test, pred_test)
cm

array([[36,  3],
       [12, 19]])

In [13]:
print(classification_report(y_test, pred_test))

              precision    recall  f1-score   support

           0       0.75      0.92      0.83        39
           1       0.86      0.61      0.72        31

    accuracy                           0.79        70
   macro avg       0.81      0.77      0.77        70
weighted avg       0.80      0.79      0.78        70



### Naive Bayes

In [14]:
nb_clf = GaussianNB()
nb_clf.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [15]:
pred_train = nb_clf.predict(X_train)
pred_test = nb_clf.predict(X_test)

In [16]:
cm = confusion_matrix(y_train, pred_train)
cm

array([[198,  65],
       [ 53,  76]])

In [17]:
print(classification_report(y_train, pred_train))

              precision    recall  f1-score   support

           0       0.79      0.75      0.77       263
           1       0.54      0.59      0.56       129

    accuracy                           0.70       392
   macro avg       0.66      0.67      0.67       392
weighted avg       0.71      0.70      0.70       392



In [18]:
cm = confusion_matrix(y_test, pred_test)
cm

array([[35,  4],
       [ 8, 23]])

In [19]:
print(classification_report(y_test, pred_test))

              precision    recall  f1-score   support

           0       0.81      0.90      0.85        39
           1       0.85      0.74      0.79        31

    accuracy                           0.83        70
   macro avg       0.83      0.82      0.82        70
weighted avg       0.83      0.83      0.83        70



# PIMA Indians Diabetes 

In [20]:
df2 = pd.read_csv("./../pima-indians-diabetes.data.csv", sep=',') 

In [21]:
df2.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Class'],
      dtype='object')

In [22]:
X = df2.drop(["Class"],axis=1)
y = df2["Class"]

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.15, shuffle=True)

### Logistic Regression

In [24]:
lr_clf = LogisticRegression(max_iter=2000)
lr_clf.fit(X_train,y_train)

/home/gykimura/miniconda3/envs/boticario/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=2000,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [25]:
pred_train = lr_clf.predict(X_train)
pred_test = lr_clf.predict(X_test)

In [26]:
cm = confusion_matrix(y_train, pred_train)
cm

array([[386,  41],
       [ 99, 126]])

In [27]:
print(classification_report(y_train, pred_train))

              precision    recall  f1-score   support

           0       0.80      0.90      0.85       427
           1       0.75      0.56      0.64       225

    accuracy                           0.79       652
   macro avg       0.78      0.73      0.74       652
weighted avg       0.78      0.79      0.78       652



In [28]:
cm = confusion_matrix(y_test, pred_test)
cm

array([[66,  7],
       [24, 19]])

In [29]:
print(classification_report(y_test, pred_test))

              precision    recall  f1-score   support

           0       0.73      0.90      0.81        73
           1       0.73      0.44      0.55        43

    accuracy                           0.73       116
   macro avg       0.73      0.67      0.68       116
weighted avg       0.73      0.73      0.71       116



### Naive Bayes

In [30]:
nb_clf = GaussianNB()
nb_clf.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [31]:
pred_train = nb_clf.predict(X_train)  
pred_test = nb_clf.predict(X_test)

In [32]:
cm = confusion_matrix(y_train, pred_train)
cm

array([[363,  64],
       [ 79, 146]])

In [33]:
print(classification_report(y_train, pred_train))

              precision    recall  f1-score   support

           0       0.82      0.85      0.84       427
           1       0.70      0.65      0.67       225

    accuracy                           0.78       652
   macro avg       0.76      0.75      0.75       652
weighted avg       0.78      0.78      0.78       652



In [34]:
cm = confusion_matrix(y_test, pred_test)
cm

array([[62, 11],
       [24, 19]])

In [35]:
print(classification_report(y_test, pred_test))

              precision    recall  f1-score   support

           0       0.72      0.85      0.78        73
           1       0.63      0.44      0.52        43

    accuracy                           0.70       116
   macro avg       0.68      0.65      0.65       116
weighted avg       0.69      0.70      0.68       116



In [36]:
print(f1_score(y_test, pred_test))

0.5205479452054794
