In [26]:
from sklearn.linear_model import SGDClassifier, RidgeClassifier, LogisticRegression
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.multiclass import OneVsRestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing
import matplotlib.pyplot as plt
from scipy.special import expit
from scipy.io import arff
import numpy as np
import pandas as pd
import scipy


# Classificador Multi Label 

Único Y, vários rótulos

## MNIST

In [2]:
df = pd.read_csv('./../../mnist_train.csv')
df = df.sample(n=3000)
df

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
1145       3    0    0    0    0    0    0    0    0    0  ...      0      0   
15165      9    0    0    0    0    0    0    0    0    0  ...      0      0   
9745       6    0    0    0    0    0    0    0    0    0  ...      0      0   
28773      3    0    0    0    0    0    0    0    0    0  ...      0      0   
36462      2    0    0    0    0    0    0    0    0    0  ...      0      0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
40547      8    0    0    0    0    0    0    0    0    0  ...      0      0   
14726      9    0    0    0    0    0    0    0    0    0  ...      0      0   
49430      2    0    0    0    0    0    0    0    0    0  ...      0      0   
35979      3    0    0    0    0    0    0    0    0    0  ...      0      0   
50850      1    0    0    0    0    0    0    0    0    0  ...      0      0   

       28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
1145       0      0      0      0      0      0      0      0  
15165      0      0      0      0      0      0      0      0  
9745       0      0      0      0      0      0      0      0  
28773      0      0      0      0      0      0      0      0  
36462      0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
40547      0      0      0      0      0      0      0      0  
14726      0      0      0      0      0      0      0      0  
49430      0      0      0      0      0      0      0      0  
35979      0      0      0      0      0      0      0      0  
50850      0      0      0      0      0      0      0      0  

[3000 rows x 785 columns]

In [3]:
df.label.value_counts()

3    324
1    324
4    319
9    308
5    304
7    301
6    297
8    287
2    272
0    264
Name: label, dtype: int64

In [4]:
X = df.drop(['label'],axis=1)
y = df[['label']]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [32]:
# Classificadores

# SGD
sgd = SGDClassifier(random_state=42)
# Logistic Regression
lr = LogisticRegression(multi_class='multinomial', solver='lbfgs')
# Naive Bayes
nb = GaussianNB()
# KNN
knn = KNeighborsClassifier(n_neighbors=3)
# Árvore de Decisão
tree = DecisionTreeClassifier()
# Random Forest
rfo = RandomForestClassifier(max_depth=2)

#### SGD

In [7]:
sgd.fit(X_train, y_train)
pred_test = sgd.predict(X_test)
cm = confusion_matrix(y_test, pred_test)

print(cm)
print(classification_report(y_test, pred_test))

/home/gykimura/miniconda3/envs/boticario/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[74  0  3  1  0  1  1  1  1  0]
 [ 0 73  2  0  0  1  1  0  3  0]
 [ 1  2 65  5  0  0  3  0  3  3]
 [ 0  2  3 70  0  2  1  0  9  1]
 [ 0  0  2  0 83  1  0  0  3  9]
 [ 2  1  0  9  2 69  2  0 16  1]
 [ 2  0  0  0  2  0 85  0  0  0]
 [ 0  0  1  1  4  0  0 75  2  3]
 [ 1  1  1  7  0  3  0  1 75  2]
 [ 2  0  1  0  4  3  0  8  6 78]]
              precision    recall  f1-score   support

           0       0.90      0.90      0.90        82
           1       0.92      0.91      0.92        80
           2       0.83      0.79      0.81        82
           3       0.75      0.80      0.77        88
           4       0.87      0.85      0.86        98
           5       0.86      0.68      0.76       102
           6       0.91      0.96      0.93        89
           7       0.88      0.87      0.88        86
           8       0.64      0.82      0.72        91
           9       0.80      0.76      0.78       102

    accuracy                           0.83       900
   macro avg       

#### Logistic Regression

In [9]:
lr.fit(X_train, y_train)
pred_test = lr.predict(X_test)
cm = confusion_matrix(y_test, pred_test)

print(cm)
print(classification_report(y_test, pred_test)) 

/home/gykimura/miniconda3/envs/boticario/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[74  0  3  0  0  2  1  1  0  1]
 [ 0 75  2  0  0  0  1  0  2  0]
 [ 1  7 68  4  0  1  0  0  1  0]
 [ 0  2  3 70  1  5  2  1  3  1]
 [ 0  0  2  0 88  0  0  0  0  8]
 [ 2  1  0  8  1 80  1  0  9  0]
 [ 0  0  0  0  4  1 84  0  0  0]
 [ 0  0  0  2  1  0  0 78  0  5]
 [ 0  2  1  7  0  9  2  1 68  1]
 [ 0  1  0  0  5  0  0  5  4 87]]
              precision    recall  f1-score   support

           0       0.96      0.90      0.93        82
           1       0.85      0.94      0.89        80
           2       0.86      0.83      0.84        82
           3       0.77      0.80      0.78        88
           4       0.88      0.90      0.89        98
           5       0.82      0.78      0.80       102
           6       0.92      0.94      0.93        89
           7       0.91      0.91      0.91        86
           8       0.78      0.75      0.76        91
           9       0.84      0.85      0.85       102

    accuracy                           0.86       900
   macro avg       

/home/gykimura/miniconda3/envs/boticario/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


#### Naive Bayes

In [10]:
nb.fit(X_train, y_train)
pred_test = nb.predict(X_test)
cm = confusion_matrix(y_test, pred_test)

print(cm)
print(classification_report(y_test, pred_test)) 

/home/gykimura/miniconda3/envs/boticario/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[67  1  5  0  0  2  1  0  5  1]
 [ 0 70  0  2  1  1  2  0  3  1]
 [ 4  4 46  0  2  3  9  0 14  0]
 [ 5  4  6 32  1  2  4  1 24  9]
 [ 4  3  0  0 46  2  2  2  6 33]
 [13  6  2  2  4 15  1  0 51  8]
 [ 1  0  3  0  0  0 83  0  2  0]
 [ 0  0  0  2  4  0  0 41  1 38]
 [ 3 15  1  2  1  4  0  0 50 15]
 [ 0  0  0  0  1  0  0  3  3 95]]
              precision    recall  f1-score   support

           0       0.69      0.82      0.75        82
           1       0.68      0.88      0.77        80
           2       0.73      0.56      0.63        82
           3       0.80      0.36      0.50        88
           4       0.77      0.47      0.58        98
           5       0.52      0.15      0.23       102
           6       0.81      0.93      0.87        89
           7       0.87      0.48      0.62        86
           8       0.31      0.55      0.40        91
           9       0.47      0.93      0.63       102

    accuracy                           0.61       900
   macro avg       

#### KNN

In [12]:
knn.fit(X_train, y_train)
pred_test = knn.predict(X_test)
cm = confusion_matrix(y_test, pred_test)

print(cm)
print(classification_report(y_test, pred_test)) 

/home/gykimura/miniconda3/envs/boticario/lib/python3.7/site-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


[[81  0  0  0  0  1  0  0  0  0]
 [ 0 79  0  0  1  0  0  0  0  0]
 [ 2  6 72  1  0  1  0  0  0  0]
 [ 1  3  5 71  0  4  0  1  0  3]
 [ 0  0  0  0 92  0  1  0  0  5]
 [ 2  2  0  6  0 87  2  0  1  2]
 [ 2  0  0  0  0  0 87  0  0  0]
 [ 0  1  0  0  4  0  0 80  0  1]
 [ 1  1  0  7  0  2  0  0 78  2]
 [ 0  0  0  1  4  1  0  6  1 89]]
              precision    recall  f1-score   support

           0       0.91      0.99      0.95        82
           1       0.86      0.99      0.92        80
           2       0.94      0.88      0.91        82
           3       0.83      0.81      0.82        88
           4       0.91      0.94      0.92        98
           5       0.91      0.85      0.88       102
           6       0.97      0.98      0.97        89
           7       0.92      0.93      0.92        86
           8       0.97      0.86      0.91        91
           9       0.87      0.87      0.87       102

    accuracy                           0.91       900
   macro avg       

#### Árvore de Decisão

In [13]:
tree.fit(X_train, y_train)
pred_test = tree.predict(X_test)
cm = confusion_matrix(y_test, pred_test)

print(cm)
print(classification_report(y_test, pred_test)) 

[[68  0  1  1  3  3  4  1  0  1]
 [ 0 72  3  3  0  0  0  0  1  1]
 [ 3  0 50  7  2  4  5  4  6  1]
 [ 1  3  6 52  0  9  3  3  5  6]
 [ 1  0  3  4 79  0  5  2  1  3]
 [ 4  1  1 13  2 59  7  2  9  4]
 [ 2  1  2  0  4  5 70  1  4  0]
 [ 0  1  1  1  1  3  0 73  2  4]
 [ 1  6  7  9  0  5  5  1 56  1]
 [ 0  0  1  2  6  2  2 12  5 72]]
              precision    recall  f1-score   support

           0       0.85      0.83      0.84        82
           1       0.86      0.90      0.88        80
           2       0.67      0.61      0.64        82
           3       0.57      0.59      0.58        88
           4       0.81      0.81      0.81        98
           5       0.66      0.58      0.61       102
           6       0.69      0.79      0.74        89
           7       0.74      0.85      0.79        86
           8       0.63      0.62      0.62        91
           9       0.77      0.71      0.74       102

    accuracy                           0.72       900
   macro avg       

#### Resultados
* Para uma amostragem de 3000 instâncias da base de dados Mnist  
* Melhor método foi o KNN (K=3), apresentando 91% de acurácia e e macro average
    * O dígito 3 apresentou o menor número de acertos, sendo erroneamente classificado cinco vezes como o dígito 2 e quatro vezes como o dígito 5.
    * O classificador teve maior sucesso em identificar o dígito 4, confundindo uma vez com dígito 6 e cinco vezes com o dígito 9

# Classificador Multi Classe

Y com várias colunas 

In [17]:
data, meta = scipy.io.arff.loadarff('./../../scene_arff.arff')
df = pd.DataFrame(data)
df

attr1     attr2     attr3     attr4     attr5     attr6     attr7  \
0     0.646467  0.666435  0.685047  0.699053  0.652746  0.407864  0.150309   
1     0.770156  0.767255  0.761053  0.745630  0.742231  0.688086  0.708416   
2     0.793984  0.772096  0.761820  0.762213  0.740569  0.734361  0.722677   
3     0.938563  0.949260  0.955621  0.966743  0.968649  0.869619  0.696925   
4     0.512130  0.524684  0.520020  0.504467  0.471209  0.417654  0.364292   
...        ...       ...       ...       ...       ...       ...       ...   
2402  0.875782  0.901653  0.926227  0.721366  0.795826  0.867642  0.794125   
2403  0.657706  0.669877  0.692338  0.713920  0.727374  0.750354  0.684372   
2404  0.952281  0.944987  0.905556  0.836604  0.875916  0.957034  0.953938   
2405  0.883990  0.899004  0.901019  0.904298  0.846402  0.858145  0.851362   
2406  0.974915  0.866425  0.818144  0.936140  0.938583  0.935087  0.930597   

         attr8     attr9    attr10  ...   attr291   attr292   attr293  \
0     0.535193  0.555689  0.580782  ...  0.157332  0.247298  0.014025   
1     0.757351  0.760633  0.740314  ...  0.251454  0.137833  0.082672   
2     0.849128  0.839607  0.812746  ...  0.017166  0.051125  0.112506   
3     0.953460  0.959631  0.966320  ...  0.019267  0.031290  0.049780   
4     0.562266  0.588592  0.584449  ...  0.198151  0.238796  0.164270   
...        ...       ...       ...  ...       ...       ...       ...   
2402  0.899067  0.908963  0.895336  ...  0.215147  0.279607  0.254413   
2403  0.718770  0.719916  0.730645  ...  0.217201  0.199491  0.048747   
2404  0.967956  0.819636  0.707311  ...  0.028002  0.031900  0.017547   
2405  0.852472  0.876665  0.908187  ...  0.239041  0.256158  0.226332   
2406  1.000000  0.806074  0.717955  ...  0.073742  0.005131  0.025059   

       attr294  Beach  Sunset  FallFoliage  Field  Mountain  Urban  
0     0.029709   b'1'    b'0'         b'0'   b'0'      b'1'   b'0'  
1     0.036320   b'1'    b'0'         b'0'   b'0'      b'0'   b'1'  
2     0.083924   b'1'    b'0'         b'0'   b'0'      b'0'   b'0'  
3     0.090959   b'1'    b'0'         b'0'   b'0'      b'0'   b'0'  
4     0.184290   b'1'    b'0'         b'0'   b'0'      b'0'   b'0'  
...        ...    ...     ...          ...    ...       ...    ...  
2402  0.134350   b'0'    b'0'         b'0'   b'0'      b'0'   b'1'  
2403  0.041638   b'0'    b'0'         b'0'   b'0'      b'0'   b'1'  
2404  0.019734   b'0'    b'0'         b'0'   b'0'      b'0'   b'1'  
2405  0.223070   b'0'    b'0'         b'0'   b'0'      b'0'   b'1'  
2406  0.004033   b'0'    b'0'         b'0'   b'0'      b'0'   b'1'  

[2407 rows x 300 columns]

In [18]:
df.columns

Index(['attr1', 'attr2', 'attr3', 'attr4', 'attr5', 'attr6', 'attr7', 'attr8',
       'attr9', 'attr10',
       ...
       'attr291', 'attr292', 'attr293', 'attr294', 'Beach', 'Sunset',
       'FallFoliage', 'Field', 'Mountain', 'Urban'],
      dtype='object', length=300)

In [19]:
X = df.drop(['Beach','Sunset','FallFoliage','Field','Mountain','Urban'],axis=1)
Y = df[['Beach','Sunset','FallFoliage','Field','Mountain','Urban']]

In [20]:
le = preprocessing.LabelEncoder()
Y['beach'] = le.fit_transform(Y['Beach'])
Y['sunset'] = le.fit_transform(Y['Sunset'])
Y['fallFoliage'] = le.fit_transform(Y['FallFoliage'])
Y['field'] = le.fit_transform(Y['Field'])
Y['mountain'] = le.fit_transform(Y['Mountain'])
Y['urban'] = le.fit_transform(Y['Urban'])

Y = Y.drop(['Beach','Sunset','FallFoliage','Field','Mountain','Urban'], axis=1)

/home/gykimura/miniconda3/envs/boticario/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/home/gykimura/miniconda3/envs/boticario/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/gykimura/miniconda3/envs/boticario/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a c

In [34]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.1)

#### Decision Tree 

In [35]:
sgd_clf = DecisionTreeClassifier()

sgd_clf.fit(X_train, Y_train)

Y_pred = sgd_clf.predict(X_test)
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.44      0.54      0.48        39
           1       0.83      0.51      0.63        37
           2       0.61      0.65      0.63        34
           3       0.71      0.61      0.66        44
           4       0.37      0.40      0.38        58
           5       0.46      0.53      0.50        49

   micro avg       0.52      0.53      0.53       261
   macro avg       0.57      0.54      0.55       261
weighted avg       0.55      0.53      0.53       261
 samples avg       0.54      0.53      0.53       261



### Múltiplas classes por instância

##### Logistic Regression

In [36]:
YY = Y[['sunset']]

In [37]:
sgd.fit(X, YY)
pred_test = sgd.predict(X)
print(classification_report(YY, pred_test))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      2043
           1       0.98      0.91      0.94       364

    accuracy                           0.98      2407
   macro avg       0.98      0.95      0.97      2407
weighted avg       0.98      0.98      0.98      2407



/home/gykimura/miniconda3/envs/boticario/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


##### KNN

In [38]:
knn.fit(X, YY)
pred_test = knn.predict(X)
print(classification_report(YY, pred_test))

/home/gykimura/miniconda3/envs/boticario/lib/python3.7/site-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


              precision    recall  f1-score   support

           0       0.96      1.00      0.98      2043
           1       0.99      0.78      0.87       364

    accuracy                           0.96      2407
   macro avg       0.97      0.89      0.92      2407
weighted avg       0.97      0.96      0.96      2407



##### Random Forest

In [39]:
rfo.fit(X, YY)
pred_test = rfo.predict(X)
print(classification_report(YY, pred_test))

              precision    recall  f1-score   support

           0       0.93      1.00      0.96      2043
           1       0.98      0.60      0.75       364

    accuracy                           0.94      2407
   macro avg       0.96      0.80      0.86      2407
weighted avg       0.94      0.94      0.93      2407



/home/gykimura/miniconda3/envs/boticario/lib/python3.7/site-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.
