In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
import seaborn as sns

from sklearn import preprocessing
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, roc_curve, roc_auc_score, classification_report

from sklearn.linear_model import LogisticRegression

from sklearn.naive_bayes import GaussianNB

#Classificadores Lineares
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import RidgeClassifier
from sklearn.linear_model import LogisticRegression

#Classificadores KNN
from sklearn.neighbors import KNeighborsClassifier

#Classificadores Naive Nayes
from sklearn.naive_bayes import MultinomialNB

#Classificadores Arvores de Decisão
from sklearn.tree import DecisionTreeClassifier

#SVM
from sklearn.svm import SVC

from sklearn.model_selection import train_test_split

from sklearn import preprocessing
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, roc_curve, roc_auc_score, classification_report

from sklearn.preprocessing import StandardScaler

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import math

from sklearn import linear_model
from scipy.special import expit

from sklearn.metrics import confusion_matrix
import scipy
from scipy.io import arff

### MNIST

In [2]:
df_train = pd.read_csv('Datasets/mnist-in-csv/mnist-in-csv/mnist_train.csv')
df_test = pd.read_csv('Datasets/mnist-in-csv/mnist-in-csv/mnist_test.csv')

In [3]:
scaler = preprocessing.MinMaxScaler()

X_train = df_train.drop(['label'], axis =1)
X_train_norm = scaler.fit_transform(X_train)
y_train = df_train['label']

In [4]:
X_test = df_test.drop(['label'], axis =1)
X_test_norm = scaler.fit_transform(X_test)

y_test = df_test['label']

In [5]:
sgd_clf = LogisticRegression()
sgd_clf.fit(X_train_norm, y_train)

y_pred = sgd_clf.predict(X_test_norm)

cm = confusion_matrix(y_test, y_pred)


print(cm)
print(classification_report(y_test, y_pred))

/home/leticia/miniconda3/envs/ambi/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/leticia/miniconda3/envs/ambi/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[ 960    0    1    2    0    5    6    3    1    2]
 [   0 1112    3    1    0    1    5    1   12    0]
 [   8    8  919   20    9    5   10   12   37    4]
 [   4    0   17  919    2   22    4   12   21    9]
 [   1    2    5    3  914    0   10    2    7   38]
 [  10    2    0   41   10  770   17    7   28    7]
 [   9    3    7    2    6   20  907    1    3    0]
 [   2    7   22    5    8    1    1  950    5   27]
 [  10   14    5   21   14   27    7   11  853   12]
 [   8    8    2   13   31   14    0   24   12  897]]
              precision    recall  f1-score   support

           0       0.95      0.98      0.96       980
           1       0.96      0.98      0.97      1135
           2       0.94      0.89      0.91      1032
           3       0.89      0.91      0.90      1010
           4       0.92      0.93      0.93       982
           5       0.89      0.86      0.88       892
           6       0.94      0.95      0.94       958
           7       0.93      0.92   

### DATASET ARFF

In [12]:
import scipy
from scipy.io import arff

data, meta = scipy.io.arff.loadarff('yeast-train.arff.txt')

data = pd.DataFrame(data)

In [13]:
X = data.drop(['Class1','Class2','Class3','Class4','Class5','Class6','Class7','Class8','Class9','Class10','Class11','Class12','Class13','Class14'], axis=1)
Y = data[['Class1','Class2','Class3','Class4','Class5','Class6','Class7','Class8','Class9','Class10','Class11','Class12','Class13','Class14']]

le = preprocessing.LabelEncoder()
Y['class1'] = le.fit_transform(Y['Class1'])
Y['class2'] = le.fit_transform(Y['Class2'])
Y['class3'] = le.fit_transform(Y['Class3'])
Y['class4'] = le.fit_transform(Y['Class4'])
Y['class5'] = le.fit_transform(Y['Class5'])
Y['class6'] = le.fit_transform(Y['Class6'])
Y['class7'] = le.fit_transform(Y['Class7'])
Y['class8'] = le.fit_transform(Y['Class8'])
Y['class9'] = le.fit_transform(Y['Class9'])
Y['class10'] = le.fit_transform(Y['Class10'])
Y['class11'] = le.fit_transform(Y['Class11'])
Y['class12'] = le.fit_transform(Y['Class12'])
Y['class13'] = le.fit_transform(Y['Class13'])
Y['class14'] = le.fit_transform(Y['Class14'])

Y = Y.drop(['Class1','Class2','Class3','Class4','Class5','Class6','Class7','Class8','Class9','Class10','Class11','Class12','Class13','Class14'], axis=1)

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.1)

/home/leticia/miniconda3/envs/ambi/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/home/leticia/miniconda3/envs/ambi/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/home/leticia/miniconda3/envs/ambi/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See 

In [21]:
# sgd_clf = DecisionTreeClassifier()
sgd_clf = KNeighborsClassifier()

print(X_train.shape)
print(Y_train.shape)
sgd_clf.fit(X_train, Y_train)
y_pred = sgd_clf.predict(X_train)
print(classification_report(Y_train, y_pred))


(1350, 103)
(1350, 14)
              precision    recall  f1-score   support

           0       0.82      0.56      0.67       426
           1       0.73      0.71      0.72       585
           2       0.76      0.74      0.75       545
           3       0.75      0.69      0.72       485
           4       0.73      0.64      0.68       390
           5       0.72      0.48      0.57       336
           6       0.76      0.37      0.50       235
           7       0.74      0.34      0.47       259
           8       0.67      0.02      0.04        87
           9       0.78      0.19      0.31       144
          10       0.73      0.20      0.31       178
          11       0.82      0.96      0.88      1022
          12       0.81      0.96      0.88      1010
          13       0.00      0.00      0.00        17

   micro avg       0.78      0.70      0.74      5719
   macro avg       0.70      0.49      0.54      5719
weighted avg       0.77      0.70      0.71      5719
 sa

/home/leticia/miniconda3/envs/ambi/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/leticia/miniconda3/envs/ambi/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels.
  'precision', 'predicted', average, warn_for)


### Dataset imagens de paisagens