In [23]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
import seaborn as sns

from sklearn import preprocessing
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, roc_curve, roc_auc_score, classification_report

from sklearn.linear_model import LogisticRegression

from sklearn.naive_bayes import GaussianNB

#Classificadores Lineares
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import RidgeClassifier
from sklearn.linear_model import LogisticRegression

#Classificadores KNN
from sklearn.neighbors import KNeighborsClassifier

#Classificadores Naive Nayes
from sklearn.naive_bayes import MultinomialNB

#Classificadores Arvores de Decisão
from sklearn.tree import DecisionTreeClassifier

#SVM
from sklearn.svm import SVC

from sklearn.model_selection import train_test_split

from sklearn import preprocessing
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, roc_curve, roc_auc_score, classification_report

from sklearn.preprocessing import StandardScaler

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import math

from sklearn import linear_model
from scipy.special import expit

from sklearn.metrics import confusion_matrix
import scipy
from scipy.io import arff


### Classificação com Multiplas Classes
* A resposta (y) ́e umas das multiplas classes possıveis

### Usando base Iris para teste
#### Variáveis independentes:

* Largura de pétala
* altura de pétala
* Largura de sépala
* altura de sépala

#### Variável a ser predita:
* Predizer: species (Nesse dataset 3 possíveis)

In [24]:
df = pd.read_csv('iris.csv')

In [25]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

### Para datasets com muitas variáveis independentes é possível eliminar apenas o label usando drop

In [42]:
#X = df[['sepal_length','sepal_width','petal_length','petal_width']]
X = df.drop(['species'], axis=1)
y = df[['species']]
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.1)

In [27]:
print( df['species'].unique())

['setosa' 'versicolor' 'virginica']


#### multi_class{‘auto’, ‘ovr’, ‘multinomial’}, default=’auto’

* Se a opção escolhida for "ovr", um problema binário é montado para cada rótulo. 
* Para "multinomial", a perda minimizada é o ajuste de perda multinomial em toda a distribuição de probabilidade, mesmo se houber apenas duas classes
* "Multinomial" fica indisponível quando solver = 'liblinear'. 
'Auto' seleciona 'ovr' se os dados são binários ou se solver = 'liblinear' caso contrário, seleciona 'multinomial'.

ref: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html?highlight=logistic%20regression#sklearn.linear_model.LogisticRegression

### solver{‘newton-cg’, ‘lbfgs’, ‘liblinear’, ‘sag’, ‘saga’}, default=’lbfgs’

* Algoritmo a ser usado na otimização.

* Para conjuntos de dados pequenos, 'liblinear' é uma boa opção, enquanto 'sag' e 'saga' são mais rápidos para conjuntos grandes de dados

* Apenas 'newton-cg', 'sag', 'saga' e 'lbfgs' lidam com a perda multinomial; 

* "Liblinear" é limitado a esquemas de um contra o resto.

In [34]:
#sgd_clf = SGDClassifier(random_state=42)
#sgd_clf = LogisticRegression(multi_class='multinomial',solver='sag')
# 'newton-cg', 'sag', 'saga' e 'lbfgs
sgd_clf = LogisticRegression()

### A matriz de confusão gerada para datasets com variável alvo possuindo mais de uma classe, é quadrada sendo seu tamanho igual a quantidade de classes

### Para esse caso três espécies, portanto matriz quadrada 3x3

In [35]:
sgd_clf.fit(X_train, y_train)

y_pred = sgd_clf.predict(X_test)

cm = confusion_matrix(y_test, y_pred)


print(cm)
print(classification_report(y_test, y_pred))

[[18  0  0]
 [ 0 12  0]
 [ 0  1 14]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        18
  versicolor       0.92      1.00      0.96        12
   virginica       1.00      0.93      0.97        15

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



/home/silvio/.conda/envs/trackml6/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/silvio/.conda/envs/trackml6/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/silvio/.conda/envs/trackml6/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


#### Interpretação
* As classes setosa e versicolor não tiverem erros (precision 1)
* A classe virginica houve 5 erros (precision 0.69)
* versicolor possui recall 0.71 => TP / TP+FN (12 / 12 + 5) => 0.7
* nesse caso, instancias da classe virginica todos foram confundidos com versicolor

### Utilizando múltiplas classes com KNN, Arvore e Naive Bayes

In [36]:
sgd_clf = KNeighborsClassifier(n_neighbors=3)

In [37]:
sgd_clf.fit(X_train, y_train)

y_pred = sgd_clf.predict(X_test)

cm = confusion_matrix(y_test, y_pred)

print(cm)
print(classification_report(y_test, y_pred))

[[18  0  0]
 [ 0 12  0]
 [ 0  2 13]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        18
  versicolor       0.86      1.00      0.92        12
   virginica       1.00      0.87      0.93        15

    accuracy                           0.96        45
   macro avg       0.95      0.96      0.95        45
weighted avg       0.96      0.96      0.96        45



/opt/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


### Arvore de Decição

In [38]:
sgd_clf = DecisionTreeClassifier()

In [39]:
sgd_clf.fit(X_train, y_train)

y_pred = sgd_clf.predict(X_test)

cm = confusion_matrix(y_test, y_pred)

print(cm)
print(classification_report(y_test, y_pred))

[[18  0  0]
 [ 0 12  0]
 [ 0  5 10]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        18
  versicolor       0.71      1.00      0.83        12
   virginica       1.00      0.67      0.80        15

    accuracy                           0.89        45
   macro avg       0.90      0.89      0.88        45
weighted avg       0.92      0.89      0.89        45



### Naive Bayes

In [43]:
sgd_clf = GaussianNB()

In [44]:
sgd_clf.fit(X_train, y_train)

y_pred = sgd_clf.predict(X_test)

cm = confusion_matrix(y_test, y_pred)

print(cm)
print(classification_report(y_test, y_pred))

[[8 0 0]
 [0 3 1]
 [0 0 3]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         8
  versicolor       1.00      0.75      0.86         4
   virginica       0.75      1.00      0.86         3

    accuracy                           0.93        15
   macro avg       0.92      0.92      0.90        15
weighted avg       0.95      0.93      0.93        15



/home/silvio/.conda/envs/trackml6/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Exemplo de classificador um contra todos

In [45]:
from sklearn.multiclass import OneVsRestClassifier

clf = OneVsRestClassifier(LogisticRegression()).fit(X_train, y_train)
clf.predict(X_test)

cm = confusion_matrix(y_test, y_pred)

print(cm)
print(classification_report(y_test, y_pred))

[[8 0 0]
 [0 3 1]
 [0 0 3]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         8
  versicolor       1.00      0.75      0.86         4
   virginica       0.75      1.00      0.86         3

    accuracy                           0.93        15
   macro avg       0.92      0.92      0.90        15
weighted avg       0.95      0.93      0.93        15



/home/silvio/.conda/envs/trackml6/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/silvio/.conda/envs/trackml6/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/silvio/.conda/envs/trackml6/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


### Exemplo de classificador aos pares

In [46]:
from sklearn.multiclass import OneVsOneClassifier

clf = OneVsRestClassifier(LogisticRegression()).fit(X_train, y_train)
clf.predict(X_test)

cm = confusion_matrix(y_test, y_pred)

print(cm)
print(classification_report(y_test, y_pred))


[[8 0 0]
 [0 3 1]
 [0 0 3]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         8
  versicolor       1.00      0.75      0.86         4
   virginica       0.75      1.00      0.86         3

    accuracy                           0.93        15
   macro avg       0.92      0.92      0.90        15
weighted avg       0.95      0.93      0.93        15



/home/silvio/.conda/envs/trackml6/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/silvio/.conda/envs/trackml6/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/silvio/.conda/envs/trackml6/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


#### Exercício Mnist
* 786 colunas de características
* coluna label identifica o número
* crie um dataframe para representar a base mnist
* crie um classificador de multiplas classes (usando a coluna label) como alvo
* interprete o resultado
* Qual valor (entre 0 a 9) o classificador teve mais sucesso em identificar?

In [ ]:
### Resolva o exercicio aqui...

In [22]:
df = pd.read_csv('mnist_train.csv')
df.describe()

label      1x1      1x2      1x3      1x4      1x5      1x6  \
count  60000.000000  60000.0  60000.0  60000.0  60000.0  60000.0  60000.0   
mean       4.453933      0.0      0.0      0.0      0.0      0.0      0.0   
std        2.889270      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.000000      0.0      0.0      0.0      0.0      0.0      0.0   
25%        2.000000      0.0      0.0      0.0      0.0      0.0      0.0   
50%        4.000000      0.0      0.0      0.0      0.0      0.0      0.0   
75%        7.000000      0.0      0.0      0.0      0.0      0.0      0.0   
max        9.000000      0.0      0.0      0.0      0.0      0.0      0.0   

           1x7      1x8      1x9  ...         28x19         28x20  \
count  60000.0  60000.0  60000.0  ...  60000.000000  60000.000000   
mean       0.0      0.0      0.0  ...      0.200433      0.088867   
std        0.0      0.0      0.0  ...      6.042472      3.956189   
min        0.0      0.0      0.0  ...      0.000000      0.000000   
25%        0.0      0.0      0.0  ...      0.000000      0.000000   
50%        0.0      0.0      0.0  ...      0.000000      0.000000   
75%        0.0      0.0      0.0  ...      0.000000      0.000000   
max        0.0      0.0      0.0  ...    254.000000    254.000000   

              28x21         28x22         28x23       28x24    28x25    28x26  \
count  60000.000000  60000.000000  60000.000000  60000.0000  60000.0  60000.0   
mean       0.045633      0.019283      0.015117      0.0020      0.0      0.0   
std        2.839845      1.686770      1.678283      0.3466      0.0      0.0   
min        0.000000      0.000000      0.000000      0.0000      0.0      0.0   
25%        0.000000      0.000000      0.000000      0.0000      0.0      0.0   
50%        0.000000      0.000000      0.000000      0.0000      0.0      0.0   
75%        0.000000      0.000000      0.000000      0.0000      0.0      0.0   
max      253.000000    253.000000    254.000000     62.0000      0.0      0.0   

         28x27    28x28  
count  60000.0  60000.0  
mean       0.0      0.0  
std        0.0      0.0  
min        0.0      0.0  
25%        0.0      0.0  
50%        0.0      0.0  
75%        0.0      0.0  
max        0.0      0.0  

[8 rows x 785 columns]

### Preparação entre variável indepentes X e variáveis alvo Y 
* Mais de uma classe possível para cada instância

###  método scipy.io.arff.loadarff 
* Método para leitura de arquivos no formato Attribute-Relation File Format (ARFF)
* Fonte de bases de dados multilabel no formato arff : https://github.com/tsoumakas/mulan/tree/master/data/multi-label
* (yeast): base de dados para estudos de proteínas


In [17]:
data, meta = scipy.io.arff.loadarff('yeast-train.arff.txt')
df = pd.DataFrame(data)
df



Att1      Att2      Att3      Att4      Att5      Att6      Att7  \
0     0.093700  0.139771  0.062774  0.007698  0.083873 -0.119156  0.073305   
1    -0.022711 -0.050504 -0.035691 -0.065434 -0.084316 -0.378560  0.038212   
2    -0.090407  0.021198  0.208712  0.102752  0.119315  0.041729 -0.021728   
3    -0.085235  0.009540 -0.013228  0.094063 -0.013592 -0.030719 -0.116062   
4    -0.088765 -0.026743  0.002075 -0.043819 -0.005465  0.004306 -0.055865   
...        ...       ...       ...       ...       ...       ...       ...   
1495 -0.119784  0.001259 -0.123645 -0.015513 -0.059683  0.091032 -0.043302   
1496  0.085327  0.058590  0.085268 -0.020897  0.068972  0.030125  0.078056   
1497  0.082526 -0.095571 -0.022019 -0.046793 -0.038360  0.041084  0.056509   
1498 -0.130830  0.008868 -0.009457 -0.058930 -0.041224  0.042269  0.117717   
1499 -0.171578 -0.066536  0.168206  0.246831  0.079555  0.016528 -0.088908   

          Att8      Att9     Att10  ...  Class5  Class6  Class7  Class8  \
0     0.005510  0.027523  0.043477  ...    b'0'    b'0'    b'0'    b'0'   
1     0.085770  0.182613 -0.055544  ...    b'0'    b'0'    b'1'    b'1'   
2     0.019603 -0.063853 -0.053756  ...    b'0'    b'0'    b'0'    b'0'   
3    -0.131674 -0.165448 -0.123053  ...    b'0'    b'0'    b'0'    b'0'   
4    -0.071484 -0.159025 -0.111348  ...    b'0'    b'0'    b'0'    b'0'   
...        ...       ...       ...  ...     ...     ...     ...     ...   
1495  0.229219 -0.071498  0.182709  ...    b'0'    b'0'    b'0'    b'0'   
1496  0.011346  0.052618  0.066093  ...    b'0'    b'0'    b'0'    b'0'   
1497  0.011749 -0.029657 -0.012198  ...    b'0'    b'1'    b'1'    b'1'   
1498  0.037388 -0.085563  0.136649  ...    b'0'    b'0'    b'0'    b'0'   
1499 -0.212926 -0.280230 -0.187064  ...    b'0'    b'0'    b'0'    b'0'   

      Class9  Class10  Class11  Class12  Class13  Class14  
0       b'0'     b'0'     b'0'     b'0'     b'0'     b'0'  
1       b'0'     b'0'     b'0'     b'1'     b'1'     b'0'  
2       b'0'     b'0'     b'0'     b'1'     b'1'     b'0'  
3       b'0'     b'0'     b'0'     b'1'     b'1'     b'1'  
4       b'0'     b'0'     b'0'     b'0'     b'0'     b'0'  
...      ...      ...      ...      ...      ...      ...  
1495    b'0'     b'0'     b'0'     b'0'     b'0'     b'0'  
1496    b'0'     b'0'     b'0'     b'1'     b'1'     b'0'  
1497    b'0'     b'0'     b'0'     b'1'     b'1'     b'0'  
1498    b'0'     b'0'     b'0'     b'1'     b'1'     b'0'  
1499    b'0'     b'0'     b'0'     b'1'     b'1'     b'0'  

[1500 rows x 117 columns]

### Preparação de dados
* Codificação de variáveis categóricas
* Separação em Treino e teste

In [18]:
X = df.drop(['Class1','Class2','Class3','Class4','Class5','Class6','Class7','Class8','Class9','Class10','Class11','Class12','Class13','Class14'], axis=1)
Y = df[['Class1','Class2','Class3','Class4','Class5','Class6','Class7','Class8','Class9','Class10','Class11','Class12','Class13','Class14']]

le = preprocessing.LabelEncoder()
Y['class1'] = le.fit_transform(Y['Class1'])
Y['class2'] = le.fit_transform(Y['Class2'])
Y['class3'] = le.fit_transform(Y['Class3'])
Y['class4'] = le.fit_transform(Y['Class4'])
Y['class5'] = le.fit_transform(Y['Class5'])
Y['class6'] = le.fit_transform(Y['Class6'])
Y['class7'] = le.fit_transform(Y['Class7'])
Y['class8'] = le.fit_transform(Y['Class8'])
Y['class9'] = le.fit_transform(Y['Class9'])
Y['class10'] = le.fit_transform(Y['Class10'])
Y['class11'] = le.fit_transform(Y['Class11'])
Y['class12'] = le.fit_transform(Y['Class12'])
Y['class13'] = le.fit_transform(Y['Class13'])
Y['class14'] = le.fit_transform(Y['Class14'])

Y = Y.drop(['Class1','Class2','Class3','Class4','Class5','Class6','Class7','Class8','Class9','Class10','Class11','Class12','Class13','Class14'], axis=1)

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.1)

/opt/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/opt/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/opt/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.or

### Aplicando regressão logística a dados multi-classe
* Método apresenta erro de mal-formato de Y, indicando que não aceita múltiplas classes

In [ ]:
sgd_clf = LogisticRegression(multi_class='multinomial',solver='lbfgs')
sgd_clf.fit(X_train, Y_train)
y_pred = sgd_clf.predict(X_train)
print(classification_report(Y_train, y_pred))

### Considerando apenas uma classe como variável a ser predita
* Regressão Logística funciona

In [ ]:
YY = Y[['class1']]

sgd_clf = LogisticRegression(multi_class='multinomial',solver='lbfgs')
#sgd_clf = LogisticRegression()
sgd_clf.fit(X, YY)
y_pred = sgd_clf.predict(X)
print(classification_report(YY, y_pred))

### No scikit-learn alguns métodos aceitam dataset multiclasse: como o DecisionTreeClassifier por exemplo

In [19]:
sgd_clf = DecisionTreeClassifier()

sgd_clf.fit(X_train, Y_train)

Y_pred = sgd_clf.predict(X_test)
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.36      0.53      0.43        34
           1       0.47      0.47      0.47        64
           2       0.53      0.47      0.50        60
           3       0.47      0.48      0.47        48
           4       0.35      0.37      0.36        43
           5       0.45      0.40      0.42        45
           6       0.71      0.47      0.56        47
           7       0.55      0.40      0.46        43
           8       0.10      0.11      0.11         9
           9       0.19      0.14      0.16        22
          10       0.28      0.17      0.21        30
          11       0.77      0.74      0.76       116
          12       0.78      0.72      0.75       116
          13       0.00      0.00      0.00         2

   micro avg       0.56      0.52      0.54       679
   macro avg       0.43      0.39      0.40       679
weighted avg       0.56      0.52      0.54       679
 samples avg       0.53   

### Outro exemplo de método que aceita múltiplas classes por instância:
* import sklearn.ensemble.ExtraTreesClassifier
* import sklearn.neighbors.KNeighborsClassifier
* import sklearn.neighbors.RadiusNeighborsClassifier
* import sklearn.ensemble.RandomForestClassifier


In [20]:
sgd_clf = KNeighborsClassifier()

sgd_clf.fit(X_train, Y_train)

Y_pred = sgd_clf.predict(X_test)
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.54      0.62      0.58        34
           1       0.62      0.61      0.61        64
           2       0.72      0.60      0.65        60
           3       0.56      0.60      0.58        48
           4       0.63      0.56      0.59        43
           5       0.52      0.24      0.33        45
           6       0.69      0.23      0.35        47
           7       0.50      0.21      0.30        43
           8       0.00      0.00      0.00         9
           9       0.00      0.00      0.00        22
          10       1.00      0.03      0.06        30
          11       0.80      0.94      0.86       116
          12       0.80      0.94      0.86       116
          13       0.00      0.00      0.00         2

   micro avg       0.69      0.59      0.64       679
   macro avg       0.53      0.40      0.41       679
weighted avg       0.66      0.59      0.59       679
 samples avg       0.70   

/home/silvio/.conda/envs/trackml6/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Comparando modelos:

* Micro average (média do total de verdadeiros positivos, falsos negativos e falsos positivos) para múltiplas classes


#### Exercício
### Dataset de Paisagens: 

* 294 atributos para descrever a imagem 
* 6 colunas para predição: Beach Sunset FallFoliage Field Mountain Urban

Arquivo: scene.arff
Fonte: https://datahub.io/machine-learning/scene

Faça um classificador multiclassse
