In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
import seaborn as sns

from sklearn import preprocessing
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, roc_curve, roc_auc_score, classification_report

from sklearn.linear_model import LogisticRegression

from sklearn.naive_bayes import GaussianNB

#Classificadores Lineares
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import RidgeClassifier
from sklearn.linear_model import LogisticRegression

#Classificadores KNN
from sklearn.neighbors import KNeighborsClassifier

#Classificadores Naive Nayes
from sklearn.naive_bayes import MultinomialNB

#Classificadores Arvores de Decisão
from sklearn.tree import DecisionTreeClassifier

#SVM
from sklearn.svm import SVC

from sklearn.model_selection import train_test_split

from sklearn import preprocessing
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, roc_curve, roc_auc_score, classification_report

from sklearn.preprocessing import StandardScaler

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import math

from sklearn import linear_model
from scipy.special import expit

from sklearn.metrics import confusion_matrix
import scipy
from scipy.io import arff


### Classificação com Multiplas Classes
* A resposta (y) ́e umas das multiplas classes possıveis

### Usando base Iris para teste
#### Variáveis independentes:

* Largura de pétala
* altura de pétala
* Largura de sépala
* altura de sépala

#### Variável a ser predita:
* Predizer: species (Nesse dataset 3 possíveis)

In [2]:
df = pd.read_csv('iris.csv')

In [3]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

### Para datasets com muitas variáveis independentes é possível eliminar apenas o label usando drop

In [4]:
#X = df[['sepal_length','sepal_width','petal_length','petal_width']]
X = df.drop(['species'], axis=1)
y = df[['species']]
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.1)

In [5]:
print( df['species'].unique())

['setosa' 'versicolor' 'virginica']


#### multi_class{‘auto’, ‘ovr’, ‘multinomial’}, default=’auto’

* Se a opção escolhida for "ovr", um problema binário é montado para cada rótulo. 
* Para "multinomial", a perda minimizada é o ajuste de perda multinomial em toda a distribuição de probabilidade, mesmo se houber apenas duas classes
* "Multinomial" fica indisponível quando solver = 'liblinear'. 
'Auto' seleciona 'ovr' se os dados são binários ou se solver = 'liblinear' caso contrário, seleciona 'multinomial'.

ref: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html?highlight=logistic%20regression#sklearn.linear_model.LogisticRegression

### solver{‘newton-cg’, ‘lbfgs’, ‘liblinear’, ‘sag’, ‘saga’}, default=’lbfgs’

* Algoritmo a ser usado na otimização.

* Para conjuntos de dados pequenos, 'liblinear' é uma boa opção, enquanto 'sag' e 'saga' são mais rápidos para conjuntos grandes de dados

* Apenas 'newton-cg', 'sag', 'saga' e 'lbfgs' lidam com a perda multinomial; 

* "Liblinear" é limitado a esquemas de um contra o resto.

In [6]:
#sgd_clf = SGDClassifier(random_state=42)
#sgd_clf = LogisticRegression(multi_class='multinomial',solver='sag')
# 'newton-cg', 'sag', 'saga' e 'lbfgs
sgd_clf = LogisticRegression()

### A matriz de confusão gerada para datasets com variável alvo possuindo mais de uma classe, é quadrada sendo seu tamanho igual a quantidade de classes

### Para esse caso três espécies, portanto matriz quadrada 3x3

In [7]:
sgd_clf.fit(X_train, y_train)

y_pred = sgd_clf.predict(X_test)

cm = confusion_matrix(y_test, y_pred)


print(cm)
print(classification_report(y_test, y_pred))

/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


[[4 0 0]
 [0 5 0]
 [0 0 6]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         4
  versicolor       1.00      1.00      1.00         5
   virginica       1.00      1.00      1.00         6

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15



#### Interpretação
* As classes setosa e versicolor não tiverem erros (precision 1)
* A classe virginica houve 5 erros (precision 0.69)
* versicolor possui recall 0.71 => TP / TP+FN (12 / 12 + 5) => 0.7
* nesse caso, instancias da classe virginica todos foram confundidos com versicolor

### Utilizando múltiplas classes com KNN, Arvore e Naive Bayes

In [8]:
sgd_clf = KNeighborsClassifier(n_neighbors=3)

In [9]:
sgd_clf.fit(X_train, y_train)

y_pred = sgd_clf.predict(X_test)

cm = confusion_matrix(y_test, y_pred)

print(cm)
print(classification_report(y_test, y_pred))

[[4 0 0]
 [0 5 0]
 [0 0 6]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         4
  versicolor       1.00      1.00      1.00         5
   virginica       1.00      1.00      1.00         6

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15



/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


### Arvore de Decição

In [10]:
sgd_clf = DecisionTreeClassifier()

In [11]:
sgd_clf.fit(X_train, y_train)

y_pred = sgd_clf.predict(X_test)

cm = confusion_matrix(y_test, y_pred)

print(cm)
print(classification_report(y_test, y_pred))

[[4 0 0]
 [0 5 0]
 [0 1 5]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         4
  versicolor       0.83      1.00      0.91         5
   virginica       1.00      0.83      0.91         6

    accuracy                           0.93        15
   macro avg       0.94      0.94      0.94        15
weighted avg       0.94      0.93      0.93        15



### Naive Bayes

In [12]:
sgd_clf = GaussianNB()

In [13]:
sgd_clf.fit(X_train, y_train)

y_pred = sgd_clf.predict(X_test)

cm = confusion_matrix(y_test, y_pred)

print(cm)
print(classification_report(y_test, y_pred))

[[4 0 0]
 [0 5 0]
 [0 0 6]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         4
  versicolor       1.00      1.00      1.00         5
   virginica       1.00      1.00      1.00         6

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15



/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Exemplo de classificador um contra todos

In [14]:
from sklearn.multiclass import OneVsRestClassifier

clf = OneVsRestClassifier(LogisticRegression()).fit(X_train, y_train)
clf.predict(X_test)

cm = confusion_matrix(y_test, y_pred)

print(cm)
print(classification_report(y_test, y_pred))

[[4 0 0]
 [0 5 0]
 [0 0 6]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         4
  versicolor       1.00      1.00      1.00         5
   virginica       1.00      1.00      1.00         6

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15



/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


### Exemplo de classificador aos pares

In [15]:
from sklearn.multiclass import OneVsOneClassifier

clf = OneVsRestClassifier(LogisticRegression()).fit(X_train, y_train)
clf.predict(X_test)

cm = confusion_matrix(y_test, y_pred)

print(cm)
print(classification_report(y_test, y_pred))


/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


[[4 0 0]
 [0 5 0]
 [0 0 6]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         4
  versicolor       1.00      1.00      1.00         5
   virginica       1.00      1.00      1.00         6

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15



#### Exercício Mnist
* 786 colunas de características
* coluna label identifica o número
* crie um dataframe para representar a base mnist
* crie um classificador de multiplas classes (usando a coluna label) como alvo
* interprete o resultado
* Qual valor (entre 0 a 9) o classificador teve mais sucesso em identificar?

In [20]:
### Resolva o exercicio aqui...
df_train = pd.read_csv('mnist-in-csv/mnist_train.csv')
df.describe()

X_train = df_train.drop(['label'], axis=1)
y_train = df_train['label']

df_test = pd.read_csv('mnist-in-csv/mnist_test.csv')

X_test = df_test.drop(['label'], axis=1)
y_test = df_test['label']

tree = DecisionTreeClassifier()

tree.fit(X_train, y_train)

y_pred = tree.predict(X_test)


print(classification_report(y_test, y_pred))
# O classificador obteve maior sucesso em identificar o numero 1 e maior dificuldade em classificar o numero 8

              precision    recall  f1-score   support

           0       0.91      0.93      0.92       980
           1       0.95      0.96      0.95      1135
           2       0.86      0.85      0.86      1032
           3       0.83      0.84      0.84      1010
           4       0.88      0.87      0.87       982
           5       0.83      0.83      0.83       892
           6       0.90      0.88      0.89       958
           7       0.90      0.91      0.90      1028
           8       0.83      0.81      0.82       974
           9       0.85      0.86      0.86      1009

    accuracy                           0.88     10000
   macro avg       0.87      0.87      0.87     10000
weighted avg       0.88      0.88      0.88     10000



In [21]:
knn = KNeighborsClassifier(n_neighbors=8, n_jobs=12)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)


print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      0.99      0.98       980
           1       0.94      1.00      0.97      1135
           2       0.98      0.95      0.97      1032
           3       0.97      0.97      0.97      1010
           4       0.97      0.96      0.97       982
           5       0.97      0.97      0.97       892
           6       0.98      0.98      0.98       958
           7       0.96      0.96      0.96      1028
           8       0.99      0.93      0.96       974
           9       0.96      0.95      0.96      1009

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000



In [17]:
df = pd.read_csv('mnist-in-csv/mnist_train.csv')
df.describe()

label      1x1      1x2      1x3      1x4      1x5      1x6  \
count  60000.000000  60000.0  60000.0  60000.0  60000.0  60000.0  60000.0   
mean       4.453933      0.0      0.0      0.0      0.0      0.0      0.0   
std        2.889270      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.000000      0.0      0.0      0.0      0.0      0.0      0.0   
25%        2.000000      0.0      0.0      0.0      0.0      0.0      0.0   
50%        4.000000      0.0      0.0      0.0      0.0      0.0      0.0   
75%        7.000000      0.0      0.0      0.0      0.0      0.0      0.0   
max        9.000000      0.0      0.0      0.0      0.0      0.0      0.0   

           1x7      1x8      1x9  ...         28x19         28x20  \
count  60000.0  60000.0  60000.0  ...  60000.000000  60000.000000   
mean       0.0      0.0      0.0  ...      0.200433      0.088867   
std        0.0      0.0      0.0  ...      6.042472      3.956189   
min        0.0      0.0      0.0  ...      0.000000      0.000000   
25%        0.0      0.0      0.0  ...      0.000000      0.000000   
50%        0.0      0.0      0.0  ...      0.000000      0.000000   
75%        0.0      0.0      0.0  ...      0.000000      0.000000   
max        0.0      0.0      0.0  ...    254.000000    254.000000   

              28x21         28x22         28x23       28x24    28x25    28x26  \
count  60000.000000  60000.000000  60000.000000  60000.0000  60000.0  60000.0   
mean       0.045633      0.019283      0.015117      0.0020      0.0      0.0   
std        2.839845      1.686770      1.678283      0.3466      0.0      0.0   
min        0.000000      0.000000      0.000000      0.0000      0.0      0.0   
25%        0.000000      0.000000      0.000000      0.0000      0.0      0.0   
50%        0.000000      0.000000      0.000000      0.0000      0.0      0.0   
75%        0.000000      0.000000      0.000000      0.0000      0.0      0.0   
max      253.000000    253.000000    254.000000     62.0000      0.0      0.0   

         28x27    28x28  
count  60000.0  60000.0  
mean       0.0      0.0  
std        0.0      0.0  
min        0.0      0.0  
25%        0.0      0.0  
50%        0.0      0.0  
75%        0.0      0.0  
max        0.0      0.0  

[8 rows x 785 columns]

### Preparação entre variável indepentes X e variáveis alvo Y 
* Mais de uma classe possível para cada instância

###  método scipy.io.arff.loadarff 
* Método para leitura de arquivos no formato Attribute-Relation File Format (ARFF)
* Fonte de bases de dados multilabel no formato arff : https://github.com/tsoumakas/mulan/tree/master/data/multi-label
* (yeast): base de dados para estudos de proteínas


In [18]:
data, meta = scipy.io.arff.loadarff('yeast-train.arff.txt')
df = pd.DataFrame(data)
df



FileNotFoundError: [Errno 2] No such file or directory: 'yeast-train.arff.txt'

### Preparação de dados
* Codificação de variáveis categóricas
* Separação em Treino e teste

In [ ]:
X = df.drop(['Class1','Class2','Class3','Class4','Class5','Class6','Class7','Class8','Class9','Class10','Class11','Class12','Class13','Class14'], axis=1)
Y = df[['Class1','Class2','Class3','Class4','Class5','Class6','Class7','Class8','Class9','Class10','Class11','Class12','Class13','Class14']]

le = preprocessing.LabelEncoder()
Y['class1'] = le.fit_transform(Y['Class1'])
Y['class2'] = le.fit_transform(Y['Class2'])
Y['class3'] = le.fit_transform(Y['Class3'])
Y['class4'] = le.fit_transform(Y['Class4'])
Y['class5'] = le.fit_transform(Y['Class5'])
Y['class6'] = le.fit_transform(Y['Class6'])
Y['class7'] = le.fit_transform(Y['Class7'])
Y['class8'] = le.fit_transform(Y['Class8'])
Y['class9'] = le.fit_transform(Y['Class9'])
Y['class10'] = le.fit_transform(Y['Class10'])
Y['class11'] = le.fit_transform(Y['Class11'])
Y['class12'] = le.fit_transform(Y['Class12'])
Y['class13'] = le.fit_transform(Y['Class13'])
Y['class14'] = le.fit_transform(Y['Class14'])

Y = Y.drop(['Class1','Class2','Class3','Class4','Class5','Class6','Class7','Class8','Class9','Class10','Class11','Class12','Class13','Class14'], axis=1)

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.1)

### Aplicando regressão logística a dados multi-classe
* Método apresenta erro de mal-formato de Y, indicando que não aceita múltiplas classes

In [ ]:
sgd_clf = LogisticRegression(multi_class='multinomial',solver='lbfgs')
sgd_clf.fit(X_train, Y_train)
y_pred = sgd_clf.predict(X_train)
print(classification_report(Y_train, y_pred))

### Considerando apenas uma classe como variável a ser predita
* Regressão Logística funciona

In [ ]:
YY = Y[['class1']]

sgd_clf = LogisticRegression(multi_class='multinomial',solver='lbfgs')
#sgd_clf = LogisticRegression()
sgd_clf.fit(X, YY)
y_pred = sgd_clf.predict(X)
print(classification_report(YY, y_pred))

### No scikit-learn alguns métodos aceitam dataset multiclasse: como o DecisionTreeClassifier por exemplo

In [ ]:
sgd_clf = DecisionTreeClassifier()

sgd_clf.fit(X_train, Y_train)

Y_pred = sgd_clf.predict(X_test)
print(classification_report(Y_test, Y_pred))

### Outro exemplo de método que aceita múltiplas classes por instância:
* import sklearn.ensemble.ExtraTreesClassifier
* import sklearn.neighbors.KNeighborsClassifier
* import sklearn.neighbors.RadiusNeighborsClassifier
* import sklearn.ensemble.RandomForestClassifier


In [ ]:
sgd_clf = KNeighborsClassifier()

sgd_clf.fit(X_train, Y_train)

Y_pred = sgd_clf.predict(X_test)
print(classification_report(Y_test, Y_pred))

Comparando modelos:

* Micro average (média do total de verdadeiros positivos, falsos negativos e falsos positivos) para múltiplas classes


#### Exercício
### Dataset de Paisagens: 

* 294 atributos para descrever a imagem 
* 6 colunas para predição: Beach Sunset FallFoliage Field Mountain Urban

Arquivo: scene.arff
Fonte: https://datahub.io/machine-learning/scene

Faça um classificador multiclassse


In [22]:
data, meta = scipy.io.arff.loadarff('scene_arff.arff')
df = pd.DataFrame(data)
df

attr1     attr2     attr3     attr4     attr5     attr6     attr7  \
0     0.646467  0.666435  0.685047  0.699053  0.652746  0.407864  0.150309   
1     0.770156  0.767255  0.761053  0.745630  0.742231  0.688086  0.708416   
2     0.793984  0.772096  0.761820  0.762213  0.740569  0.734361  0.722677   
3     0.938563  0.949260  0.955621  0.966743  0.968649  0.869619  0.696925   
4     0.512130  0.524684  0.520020  0.504467  0.471209  0.417654  0.364292   
...        ...       ...       ...       ...       ...       ...       ...   
2402  0.875782  0.901653  0.926227  0.721366  0.795826  0.867642  0.794125   
2403  0.657706  0.669877  0.692338  0.713920  0.727374  0.750354  0.684372   
2404  0.952281  0.944987  0.905556  0.836604  0.875916  0.957034  0.953938   
2405  0.883990  0.899004  0.901019  0.904298  0.846402  0.858145  0.851362   
2406  0.974915  0.866425  0.818144  0.936140  0.938583  0.935087  0.930597   

         attr8     attr9    attr10  ...   attr291   attr292   attr293  \
0     0.535193  0.555689  0.580782  ...  0.157332  0.247298  0.014025   
1     0.757351  0.760633  0.740314  ...  0.251454  0.137833  0.082672   
2     0.849128  0.839607  0.812746  ...  0.017166  0.051125  0.112506   
3     0.953460  0.959631  0.966320  ...  0.019267  0.031290  0.049780   
4     0.562266  0.588592  0.584449  ...  0.198151  0.238796  0.164270   
...        ...       ...       ...  ...       ...       ...       ...   
2402  0.899067  0.908963  0.895336  ...  0.215147  0.279607  0.254413   
2403  0.718770  0.719916  0.730645  ...  0.217201  0.199491  0.048747   
2404  0.967956  0.819636  0.707311  ...  0.028002  0.031900  0.017547   
2405  0.852472  0.876665  0.908187  ...  0.239041  0.256158  0.226332   
2406  1.000000  0.806074  0.717955  ...  0.073742  0.005131  0.025059   

       attr294  Beach  Sunset  FallFoliage  Field  Mountain  Urban  
0     0.029709   b'1'    b'0'         b'0'   b'0'      b'1'   b'0'  
1     0.036320   b'1'    b'0'         b'0'   b'0'      b'0'   b'1'  
2     0.083924   b'1'    b'0'         b'0'   b'0'      b'0'   b'0'  
3     0.090959   b'1'    b'0'         b'0'   b'0'      b'0'   b'0'  
4     0.184290   b'1'    b'0'         b'0'   b'0'      b'0'   b'0'  
...        ...    ...     ...          ...    ...       ...    ...  
2402  0.134350   b'0'    b'0'         b'0'   b'0'      b'0'   b'1'  
2403  0.041638   b'0'    b'0'         b'0'   b'0'      b'0'   b'1'  
2404  0.019734   b'0'    b'0'         b'0'   b'0'      b'0'   b'1'  
2405  0.223070   b'0'    b'0'         b'0'   b'0'      b'0'   b'1'  
2406  0.004033   b'0'    b'0'         b'0'   b'0'      b'0'   b'1'  

[2407 rows x 300 columns]

In [25]:
X = df.drop(['Beach','Sunset','FallFoliage','Mountain','Urban'], axis=1)
Y = df[['Beach','Sunset','FallFoliage','Mountain','Urban']]

le = preprocessing.LabelEncoder()
Y['Beach'] = le.fit_transform(Y['Beach'])
Y['Sunset'] = le.fit_transform(Y['Sunset'])
Y['FallFoliage'] = le.fit_transform(Y['FallFoliage'])
Y['Mountain'] = le.fit_transform(Y['Mountain'])
Y['Urban'] = le.fit_transform(Y['Urban'])

#Y = Y.drop(['Beach','Sunset','FallFoliage','Mountain','Urban'], axis=1)

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.1)

/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = valu

In [33]:
X_train

attr1     attr2     attr3     attr4     attr5     attr6     attr7  \
2025  0.617068  0.628798  0.646405  0.665450  0.685973  0.688777  0.693232   
1498  0.248967  0.297908  0.362372  0.435334  0.525943  0.578541  0.558132   
1119  0.600747  0.633892  0.655035  0.694504  0.710510  0.689767  0.654365   
2144  0.827845  0.828814  0.829645  0.826850  0.841996  0.824409  0.793373   
1134  0.206207  0.212935  0.263953  0.410147  0.340976  0.292023  0.253608   
...        ...       ...       ...       ...       ...       ...       ...   
1877  0.380992  0.449990  0.504832  0.557839  0.603147  0.613415  0.605494   
4     0.512130  0.524684  0.520020  0.504467  0.471209  0.417654  0.364292   
17    0.440256  0.489002  0.534474  0.553284  0.567649  0.566810  0.557698   
1323  0.642848  0.640235  0.651147  0.648433  0.630755  0.615422  0.597133   
696   0.977766  0.980804  0.974911  0.941395  0.752848  0.603767  0.581409   

         attr8     attr9    attr10  ...   attr286   attr287   attr288  \
2025  0.702317  0.718660  0.725616  ...  0.000782  0.001316  0.003359   
1498  0.294879  0.349496  0.431823  ...  0.104691  0.067472  0.021799   
1119  0.630110  0.688345  0.721997  ...  0.016305  0.016987  0.059548   
2144  0.855572  0.856029  0.862680  ...  0.229602  0.271889  0.184754   
1134  0.213829  0.298926  0.418848  ...  0.290775  0.301840  0.679944   
...        ...       ...       ...  ...       ...       ...       ...   
1877  0.429513  0.484929  0.481959  ...  0.760621  0.618755  0.131865   
4     0.562266  0.588592  0.584449  ...  0.023177  0.129994  0.167709   
17    0.671836  0.712883  0.735640  ...  0.250637  0.126859  0.269230   
1323  0.697602  0.581560  0.641794  ...  0.234771  0.049793  0.057771   
696   0.719703  0.727587  0.723511  ...  0.070820  0.125821  0.068049   

       attr289   attr290   attr291   attr292   attr293   attr294  Field  
2025  0.006104  0.007180  0.022375  0.010380  0.005132  0.002450   b'0'  
1498  0.053322  0.117203  0.222781  0.163611  0.109735  0.178380   b'0'  
1119  0.030031  0.024171  0.019183  0.020275  0.014107  0.020303   b'0'  
2144  0.133429  0.281802  0.117910  0.152006  0.228537  0.186173   b'0'  
1134  0.545042  0.663586  0.229375  0.589030  0.638963  0.324504   b'0'  
...        ...       ...       ...       ...       ...       ...    ...  
1877  0.319508  0.320980  0.337625  0.272396  0.444576  0.475472   b'1'  
4     0.226580  0.218534  0.198151  0.238796  0.164270  0.184290   b'0'  
17    0.137096  0.137109  0.178980  0.333771  0.163273  0.124642   b'0'  
1323  0.125030  0.126992  0.020646  0.057262  0.269526  0.357331   b'0'  
696   0.103223  0.063448  0.076434  0.093171  0.073898  0.081726   b'1'  

[2166 rows x 295 columns]

In [34]:
Y_train

Beach  Sunset  FallFoliage  Mountain  Urban
2025      0       0            0         1      0
1498      0       1            0         0      0
1119      0       0            0         0      1
2144      0       0            0         1      0
1134      0       0            0         0      1
...     ...     ...          ...       ...    ...
1877      0       0            0         0      0
4         1       0            0         0      0
17        1       0            0         0      0
1323      1       0            0         1      0
696       0       0            0         0      0

[2166 rows x 5 columns]

In [26]:
sgd_clf = DecisionTreeClassifier()

sgd_clf.fit(X_train, Y_train)

Y_pred = sgd_clf.predict(X_test)
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.61      0.74      0.67        38
           1       0.74      0.66      0.70        35
           2       0.69      0.64      0.67        42
           3       0.36      0.37      0.36        43
           4       0.37      0.41      0.39        46

   micro avg       0.53      0.55      0.54       204
   macro avg       0.55      0.56      0.56       204
weighted avg       0.54      0.55      0.55       204
 samples avg       0.46      0.46      0.46       204



/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels.
  'precision', 'predicted', average, warn_for)
/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels.
  'recall', 'true', average, warn_for)


In [36]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_jobs=12)

rf.fit(X_train, Y_train)

y_pred = rf.predict(X_test)


print(classification_report(Y_test, y_pred))

/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


              precision    recall  f1-score   support

           0       0.91      0.55      0.69        38
           1       1.00      0.60      0.75        35
           2       0.97      0.74      0.84        42
           3       0.68      0.35      0.46        43
           4       0.86      0.41      0.56        46

   micro avg       0.89      0.52      0.66       204
   macro avg       0.89      0.53      0.66       204
weighted avg       0.88      0.52      0.65       204
 samples avg       0.44      0.44      0.44       204



/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels.
  'precision', 'predicted', average, warn_for)
/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels.
  'recall', 'true', average, warn_for)


In [37]:
from sklearn.ensemble import ExtraTreesClassifier

etc = ExtraTreesClassifier(n_jobs=12)

etc.fit(X_train, Y_train)

y_pred = etc.predict(X_test)


print(classification_report(Y_test, y_pred))

/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


              precision    recall  f1-score   support

           0       0.95      0.55      0.70        38
           1       0.95      0.51      0.67        35
           2       0.90      0.67      0.77        42
           3       0.65      0.30      0.41        43
           4       0.69      0.20      0.31        46

   micro avg       0.85      0.44      0.58       204
   macro avg       0.83      0.45      0.57       204
weighted avg       0.82      0.44      0.56       204
 samples avg       0.37      0.37      0.37       204



/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels.
  'precision', 'predicted', average, warn_for)
/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels.
  'recall', 'true', average, warn_for)


In [38]:
sgd_clf = KNeighborsClassifier(n_jobs=12)

sgd_clf.fit(X_train, Y_train)

Y_pred = sgd_clf.predict(X_test)
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.88      0.61      0.72        38
           1       0.92      0.69      0.79        35
           2       0.92      0.83      0.88        42
           3       0.69      0.58      0.63        43
           4       0.64      0.78      0.71        46

   micro avg       0.79      0.70      0.74       204
   macro avg       0.81      0.70      0.74       204
weighted avg       0.80      0.70      0.74       204
 samples avg       0.59      0.59      0.59       204



/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels.
  'precision', 'predicted', average, warn_for)
/home/vitorbezerra/miniconda3/envs/amb1/lib/python3.7/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels.
  'recall', 'true', average, warn_for)
